### ISSUE TITLE
Include instructions to update weekly slides

### ISSUE THREAD

**Issue by levinwil** [NeuroDataDesign/neurodatadesign.github.io#16]
Weekly Slides link: https://docs.google.com/presentation/d/1oh12uzdPy-jnxozpedrtm6hROyZNiUZKd0M7bC8So20/edit#slide=id.g87d304a7ac_1_0

**Comment by v715** [comment]
@levinwil think you meant to put this and #17 in neurodata.io

this is for NDD!

**Comment by levinwil** [comment]
@v715 yes I did! Thanks for the catch!
