### ISSUE TITLE
Project ideas for NDD 20-21

### ISSUE THREAD

**Issue by bdpedigo** [NeuroDataDesign/neurodatadesign.github.io#4]
Please leave comments describing ideas for projects below.

**Comment by bdpedigo** [comment]
PR AutoGMM/GaussianCluster into Sklearn

**Comment by jovo** [comment]
PR ZG(2) into sklearn

**Comment by bdpedigo** [comment]
Write Python implementation of NBLAST or any other useful computational geometry distances for single neurons, make it easy to use on various data representations (e.g. swc, CATMAID, etc.)

**Comment by rmehta004** [comment]
LF/UF in a nice package.

**Comment by rmehta004** [comment]
LF+MORF+Image experiments.

**Comment by bdpedigo** [comment]
A nice implementation of GMM on unit hypersphere

**Comment by rmehta004** [comment]
MORF+time series

**Comment by v715** [comment]
Deep dive into ABIDE I/II data sets
- jaewon's idea of using MGCx to estimate connectomes from fMRI
- cluster autism data using USPORF
- compare to mouse results

**Comment by jovo** [comment]
ABIDE I/II data is getting kinda old, maybe we could use some updated data,
eg, NKI Enhanced, HCP, or data from Ted Satterthwaite.

On Mon, Jul 27, 2020 at 11:43 PM Vivek Gopalakrishnan <
notifications@github.com> wrote:

>
> *      External Email - Use Caution      *
>
>
>
> Deep dive into ABIDE I/II data sets
>
>    - jaewon's idea of using MGCx to estimate connectomes from fMRI
>    - cluster autism data using USPORF
>    - compare to mouse results
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNeuroDataDesign%2Fneurodatadesign.github.io%2Fissues%2F4%23issuecomment-664758256&data=02%7C01%7Cjovo%40jhu.edu%7C2712d2eba07540e13c1708d832a85b76%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637315045952847258&sdata=fpnpB8YWBlnDnNV4ACsiGM1o3n4HwXvQ2oPhPyuAPRU%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4WNPGMAIU7OGVHWW2LR5ZCM7ANCNFSM4MGBV3YQ&data=02%7C01%7Cjovo%40jhu.edu%7C2712d2eba07540e13c1708d832a85b76%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637315045952847258&sdata=aQUeHUmVKv6GU3DpfMjTNM90TuseONCpcfb3S6xPfQc%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time
